# Generated by Django 5.1.7 on 2025-08-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
