# Generated by Django 5.1.7 on 2025-08-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_auth', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
